# Build settings
# markdown: kramdown
# remote_theme: nrandecker/particle

# Site settings
title: Impulsx.github.io
description: uwu page
baseurl: "/Impulsx.github.io" # the subpath of your site, e.g. /blog/
# baseurl: "/particle" # the subpath of your site, e.g. /blog
url: "Impulsx.github.io"
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Impulsx
user_description: uwu
user_title: Useless, Worthless, and a PoS
email: "[REDACTED]"
# twitter_username: lorem_ipsum
github_username:  Impulsx
# gplus_username:  lorem_ipsum

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
